root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  bin = "tmp/app"
  cmd = "CGO_ENABLED=0 go build -o tmp/app app/cmd/server/main.go"
  exclude_dir = ["tmp", "testdata", "local"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = true
  include_dir = ["app"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  stop_on_error = true

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true

[misc]
  clean_on_exit = true
